spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/yomu_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8082

supabase.url=${SUPABASE_URL:}
supabase.jwt.issuer=${SUPABASE_JWT_ISSUER:}
supabase.jwt.audience=${SUPABASE_JWT_AUDIENCE:authenticated}
supabase.jwks-url=${SUPABASE_JWKS_URL:}

spring.config.import=optional:file:.env.local[.properties]

# URL be-achievement service
achievement.service.url=http://be-achievement:8083

auth.service.url=http://localhost:8081